### ISSUE TITLE
Document settings

### ISSUE THREAD

**Issue by bvizureanu** [code4romania/monitorizare-vot#100]
Provide documentation for every setting available

Provide standard and example for environment variables use

Remove comments from appsettings.json

https://github.com/code4romania/monitorizare-vot/wiki/Application-Settings - fill in this page

**Comment by KrzysztofMadejski** [comment]
Why not in the `appsettings.json`? That seems as a good place to do it. Or you prefer to have in centralized in the docs?

This issue references #51 .

**Comment by aniri** [comment]
closing this as docs were added in the wiki https://github.com/code4romania/monitorizare-vot/wiki :wink:
