### ISSUE TITLE
Feature: Teams 

### ISSUE THREAD

**Issue by KrzysztofMadejski** [code4romania/monitorizare-vot#103]
In the methodology used in Polish remote observation in Oct 2018 by "Obserwatorzy w działaniu" we had a concept of teams. Teams were 2 observers going together from station to station and registering observations. They were supposed to agree on the results together (debate what's right) and send one observation. Both observers were registered in the app, but after [data wrangling](https://github.com/code4romania/monitorizare-vot-ong/issues/52) we had a concept of a team observation rather than each observers him/herself.

**Comment by RaduCStefanescu** [comment]
Issue added in features of new version of the app.
