### ISSUE TITLE
Translate codebase to English

### ISSUE THREAD

**Issue by KrzysztofMadejski** [code4romania/monitorizare-vot#104]
There are some devs interesting in working on that in Poland, but it's hard to touch this codebase as it is all in Romanian. It would be great to refactor it to English. CC @bvizureanu 

- [ ] We should do a vocabulary of terms so we use it consistently across codebase and translations -> https://github.com/code4romania/monitorizare-vot/wiki/Vocabulary
- [ ] Do the actual translation of code
- [ ] independently, translate API #50

**Comment by RaduCStefanescu** [comment]
This issue is already fixed in the latest versions of the API.
