### ISSUE TITLE
NGO API and Mobile API should share the same datamodel

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/monitorizare-vot#111]
Merge datamodel NGO API from https://github.com/code4romania/monitorizare-vot-ong and datamodel mobile API from https://github.com/code4romania/monitorizare-vot into a single backend dependency that needs to be shared by both projects.

The domain models are started to be shared by the NGO solution and the mobile app and coordinating over the database is not a proper solution anymore:
- form data model - will be inserted from NGO solution and pulled to mobile devices
- observer data model - this is more of a case where the 2 apps interact at the boundaries of the domain models - NGO API defines the observer domain model, but the mobile app updates attributes for the observer - location, voting section, etc. Consistent data means pulling information from 2 APIs, which is not a valid solution.

**Comment by bvizureanu** [comment]
this is done in /refactor/major-wip
