### ISSUE TITLE
Migrate/translate missing ONG endpoints to the new centralized api

### ISSUE THREAD

**Issue by trupci** [code4romania/monitorizare-vot#128]
Migrate the Answers, Statistics, Jwt endpoints from the ONG api, to the new, centralized api.

**Comment by RaduCStefanescu** [comment]
I think we can close this one, right @trupci ?

**Comment by trupci** [comment]
Not exactly, I think we're still missing the `Statistics` endpoints.

**Comment by idormenco** [comment]
@trupci @RaduCStefanescu i can handle this.

**Comment by trupci** [comment]
Remaining endpoints (statistics) were integrated in [157](https://github.com/code4romania/monitorizare-vot/pull/157)
