### ISSUE TITLE
Single authentication endpoint for mobile and web

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/monitorizare-vot#129]
Integrate the `/api/v1/access` and `/api/v1/auth` into a single endpoint.

Changes should be done in branch `refactor/major-wip`

Test environment: https://mv-mobile-test.azurewebsites.net/swagger/index.html

**Comment by idormenco** [comment]
I can pick this up.

**Comment by RaduCStefanescu** [comment]
In progress @idormenco

**Comment by idormenco** [comment]
PR https://github.com/code4romania/monitorizare-vot/pull/135

**Comment by RaduCStefanescu** [comment]
Fixed in #135
