### ISSUE TITLE
Observers feature

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/monitorizare-vot#131]
Implement PUT DELETE on Observer endpoint

Implement import feature on Observer endpoint `/api/v1/observer/import`

Branch: `refactor/major-wip`

Test environment: https://mv-mobile-test.azurewebsites.net/swagger/index.html

**Comment by trupci** [comment]
I can pick this up. Can i get more details on the import feature?

**Comment by RaduCStefanescu** [comment]
@trupci 
some more details for the import can be found in this issue: https://github.com/code4romania/monitorizare-vot/issues/139

**Comment by RaduCStefanescu** [comment]
The 2 features: PUT/DELETE and import have been implemented in 
#136 #142
