### ISSUE TITLE
[Forms] CRUD Operations on `Option`

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/monitorizare-vot#132]
Test that POST on `/api/v1/form` works as expected

Implement CRUD operation on Option entity on `/api/v1/option`

Branch: `refactor/major-wip`

Test environment: https://mv-mobile-test.azurewebsites.net/swagger/index.html

**Comment by idormenco** [comment]
I can handle this. Who can perform CRUD operations on Option NgoAdmins ?

**Comment by RaduCStefanescu** [comment]
Yes, this is an NgoAdmin operation.

**Comment by RaduCStefanescu** [comment]
In progress @idormenco

**Comment by RaduCStefanescu** [comment]
Implemented in #147
