### ISSUE TITLE
[Observer] Remove IdNgo from create Observer endpoint

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/monitorizare-vot#138]
Remove IdNgo from POST /api/v1/observer endpoint.
The ngo id should be retrieved from claims.

**Comment by trupci** [comment]
Hi. I fixed this in [#136](https://github.com/code4romania/monitorizare-vot/pull/136)

**Comment by RaduCStefanescu** [comment]
In progress @trupci

**Comment by RaduCStefanescu** [comment]
Fixed in #136
