### ISSUE TITLE
Build-ul automat nu restaureaza pachetele nuget

### ISSUE THREAD

**Issue by dhont** [code4romania/monitorizare-vot#14]
Este valabil pentru TFSOnline si Appvoyeur

**Comment by dhont** [comment]
Trebuie adaugat in evenimentul de prebuild comanda dotnet restore
Functioneaza in appveyor, should work si pe TFS, @bvizureanu

**Comment by bvizureanu** [comment]
l-am facut sa mearga si in vsonline build (vNext)
incerc si un deploy in azure
