### ISSUE TITLE
[Bug] Wrong format for login response

### ISSUE THREAD

**Issue by aniri** [code4romania/monitorizare-vot#155]
POST to `/api/v1/access/authorize` returns just a string (the access token) and not a json object (with a key that holds the access token). Please refactor this method to return a properly formatted response that is consistent with the rest of the responses.

Check response from `/api/v1/access/token` for the correct response format.

**Comment by idormenco** [comment]
on it

**Comment by bvizureanu** [comment]
@aniri, this was merged, can you check after it's being deployed and close this if the case?

**Comment by aniri** [comment]
looking good!
