### ISSUE TITLE
[Bug] Retrieve Answers returns empty object

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/monitorizare-vot#161]
A call to this endpoint `https://mv-mobile-test.azurewebsites.net/api/v1/answers/filledIn?idPollingStation=2&idObserver=4` on the testing environment is returning an empty list.

Expectation would be to get the results that are saved in the database for that observer and that particular polling station.

**Comment by idormenco** [comment]
On it

**Comment by RaduCStefanescu** [comment]
Issue resolved in #167
