### ISSUE TITLE
[Polling stations] Import of all polling stations returns 502 Bad Gateway

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/monitorizare-vot#163]
When importing all the polling stations, the call fails with 502 Bad Gateway and message:
`The specified CGI application encountered an error and the server terminated the process.`

This is the import file
[Total_2019.xlsx](https://github.com/code4romania/monitorizare-vot/files/3793976/Total_2019.xlsx)

**Comment by paul-antal** [comment]
I'm on it

**Comment by RaduCStefanescu** [comment]
in progress @paul-antal

**Comment by bvizureanu** [comment]
```The property 'IdPollingStation' on entity type 'PollingStationInfo' is part of a key and so cannot be modified or marked as modified. To change the principal of an existing entity with an identifying foreign key first delete the dependent and invoke 'SaveChanges' then associate the dependent with the new principal.```

**Comment by bvizureanu** [comment]
posiible causes:
```requests taking a long time
application using high memory/CPU
application crashing due to an exception.```

I have increased the timeout for the hosting appservice to 1h. can you please check again and at least narrow down if the first item is causing the issue?
If not, we might need to increase the resources available for the current appservice.

**Comment by idormenco** [comment]
@RaduCStefanescu i found that if you upload polling stations and you have polling stations in your tables (db) it will throw an error

**Comment by RaduCStefanescu** [comment]
Good point @idormenco I cleaned the polling stations table entries
@bvizureanu still failing after about 2 minutes with
`The specified CGI application encountered an error and the server terminated the process.`

**Comment by bvizureanu** [comment]
commit https://github.com/code4romania/monitorizare-vot/commit/dc0af70a6e0ad5739e49871b1c102dac85d7c376 should improve the performance dramatically for the insert operation. 
should be <20s now..

**Comment by bvizureanu** [comment]
also, hardcoded the starting ID to be `100` instead of `1`. no conflicts should arise in testing now.. (make sure you delete the entries (with `ID>100` to retry)

**Comment by bvizureanu** [comment]
@RaduCStefanescu is this still needed?

**Comment by RaduCStefanescu** [comment]
This is fixed now, closing it.
