### ISSUE TITLE
[Push Notifications] Send notification message in Notification field as well

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/monitorizare-vot#168]
Currently the details of the notification are sent only on the `Data` field.
The details need to be sent on the `Notification` field as well, to cater for different processing on iOS and Android platforms.

Have a look at this PR: 
https://github.com/code4romania/monitorizare-vot/pull/151

**Comment by aniri** [comment]
See more details and JSON examples to be sent to Firebase here: https://firebase.google.com/docs/cloud-messaging/concept-options

Please fill in, for all push notification sent, both the `notification` and `data` json fields.

Both should have the same keys for now: `title` and `body`.

```
"notification":{
      "title":"Portugal vs. Denmark",
      "body":"great match!"
    }
```

```
"data":{
      "title":"Portugal vs. Denmark",
      "body":"great match!"
    }
```

**Comment by trupci** [comment]
I'll have a look at this one.
