### ISSUE TITLE
[Push notifications] Sending a new firebase token for a user should overwrite the old one

### ISSUE THREAD

**Issue by aniri** [code4romania/monitorizare-vot#169]
Currently when calling **POST** `/api/v1/notification/register` for a user, a new entry is created in `NotificationRegistrationData` each time. 

Expected behaviour: if the user already has a stored token, it should be overwritten with the new value.

**Comment by trupci** [comment]
On it.

**Comment by trupci** [comment]
[here](https://github.com/code4romania/monitorizare-vot/pull/171)

**Comment by aniri** [comment]
tested :smile:
