### ISSUE TITLE
Return forms ordered by day not by type

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/monitorizare-vot#184]
We need to return the forms grouped by day, not by type.

**Comment by bvizureanu** [comment]
what endpoint are you referring to?

**Comment by aniri** [comment]
@bvizureanu to `GET /api/v1/form`, the one that returns the list of available forms. we now have a lot of forms because the elections last for 3 days. they are now returned sorted by type and they should be sorted by voting day.

**Comment by idormenco** [comment]
on it
