### ISSUE TITLE
`Form Version` v2.0

### ISSUE THREAD

**Issue by bvizureanu** [code4romania/monitorizare-vot#189]
how about we solve the diaspora flag in a more general way - reusable in other circumstances as well

how about we take the form version a bit more serious?
add the form version number to the answers when we store them.
loosen the FK constraint on the answers table and avoid conflicts

abuse the version switch flag and reuse the same form in each day
just increase the version the next morning.
the forms are updated automagically and the observers' answers from the previous day will be cleared

ps: we'll need to adjust the reports' queries as well but hey..

**Comment by aniri** [comment]
@bvizureanu I think this is not applicable anymore. or should we try and add the forms version no to the answers?
