### ISSUE TITLE
Exclude results sent by test observers from statistics

### ISSUE THREAD

**Issue by bvizureanu** [code4romania/monitorizare-vot#207]
generic implementation for #206

Update:

> the `isTestObserver` flag was added in the `Observers` table. it can be used to filter out from the statistics the results sent by these observers.
> 
> filter out responses sent by test observers from the results returned by all the endpoints in the `StatisticsController`

**Comment by aniri** [comment]
the isTestObserver flag was added in the Observers table. it can be used to filter out  form the statistics the results sent by these observers.

**Comment by ardelandrei** [comment]
I could work on this issue.

Can you confirm that all these endpoints are still in usage?

Thank you!

**Comment by aniri** [comment]
@ardelandrei yes,all  the endpoints are or will be used
