### ISSUE TITLE
Implement `/health` endpoint

### ISSUE THREAD

**Issue by bvizureanu** [code4romania/monitorizare-vot#211]
Add HealthChecks to all the APIs and their dependencies

https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/health-checks?view=aspnetcore-3.1

DB
FileStorage (BLOB or local)
FireBase
Redis (if enabled)

**Comment by adrianiftode** [comment]
Would you consider [ASP.NET support](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/health-checks?view=aspnetcore-2.2) for this concern?

**Comment by RaduCStefanescu** [comment]
@bvizureanu can you comment please on the above suggestion from @adrianiftode

**Comment by idormenco** [comment]
@bvizureanu can i steal this ?

**Comment by adrianiftode** [comment]
@idormenco I would like to jump on this one too :)

**Comment by idormenco** [comment]
@adrianiftode let's talk on slack about this :)

**Comment by adrianiftode** [comment]
what's the slack workspace?

**Comment by RaduCStefanescu** [comment]
@adrianiftode you have an invite in your mailbox.
