### ISSUE TITLE
NGO management

### ISSUE THREAD

**Issue by aniri** [code4romania/monitorizare-vot#245]
Add the endpoints for managing NGOs and NGO admin accounts.  _These actions should only allowed for to admin account (an ngo admin belonging to an ngo that has the organizer flag set to true)_

CRUD for NGOs - also include the new `active` flag https://github.com/code4romania/monitorizare-vot/issues/244

Add the possibility of adding an NGO admin account.

Needed functionalities:
- view the list of ngos
- add new ngo / edit existing one
- mark ngo as active / inactive
- mark ngo as organiser / not organiser

- view / add / edit ngo admin accounts

Current data model:
ngos: shortName, Name, Organizer flag, active flag
ngo admins: account, password
 
Suggestion of needed endpoints:
- GET `/api/v1/ngo`
- GET `/api/v1/ngo/{id}`
- POST `/api/v1/ngo/{id}`
- DELETE `/api/v1/ngo/{id}`
- please suggest endpoint for updating organiser flag for ngo
- please suggest endpoint for updating ngo status

- POST  `/api/v1/ngo/{id}/ngoadmin` - add / edit admin account for an ngo
- GET `/api/v1/ngo/{id}/ngoadmin` - list all admin account for the {id} ngo

**Comment by idormenco** [comment]
i will do this

**Comment by catileptic** [comment]
This issue is up for grabs, since it seems nobody is actively working on it at the moment.

**Comment by idormenco** [comment]
@catileptic i will create a pr soon , please leave it to me
