### ISSUE TITLE
[Counties] Feature to load information about counties

### ISSUE THREAD

**Issue by aniri** [code4romania/monitorizare-vot#253]
Information about counties should be loaded in the NGO admin panel via CSV file.

The format file should be downloaded, the user needs to fill in the information required for the import of the counties information.
Tasks:
- [ ] BE: Add endpoint to download file formatted for counties import (CSV)  - _action only allowed for to admin account (an ngo admin belonging to an ngo that has the organizer flag set to true)_
`GET api/v1/county/csvFormat` - download existing county info in csv format
- [ ] BE: Add endpoint to receive updated CSV file, save the information as counties objects  - _action only allowed for to admin account (an ngo admin belonging to an ngo that has the organizer flag set to true)_
`POST api/v1/county/import`

**Comment by idormenco** [comment]
on it
