### ISSUE TITLE
[Counties] Add basic CRUD endpoints for managing counties

### ISSUE THREAD

**Issue by aniri** [code4romania/monitorizare-vot#254]
Information about counties should be displayed in the NGO admin panel. It should also be editable.

Tasks:
- [ ] Add endpoint to view all the counties
`GET api/v1/county`
- [ ] Add endpoint to edit a county - _action only allowed for to admin account (an ngo admin belonging to an ngo that has the organizer flag set to true)_
`POST api/v1/county/{id}`

**Comment by idormenco** [comment]
mine
