### ISSUE TITLE
[Polling Stations] Add CRUD endpoints for managing polling stations

### ISSUE THREAD

**Issue by aniri** [code4romania/monitorizare-vot#255]
Information about polling stations should be displayed in the NGO admin panel. It should also be editable.

:exclamation: do not delete old endpoints in order to keep backwards compatibility with older client app versions

Endpoints to be added:

- [ ] Add endpoint to view all the polling stations
`GET api/v2/polling-station`
- [ ] Add endpoint to edit a polling station _- action only allowed for to admin account (an ngo admin belonging to an ngo that has the organizer flag set to true)_
`POST api/v2/polling-station/{id}`

Update polling-station-info related endpoints (also keep the old ones for backwards compatibility):
- [ ] Add endpoint to post polling station infos (copy functionality from `POST api/v1/polling-station`)
`POST api/v2/polling-station-info`
- [ ] Add endpoint to put polling station infos (copy functionality from`PUT api/v1/polling-station`)
`PUT api/v2/polling-station-info`

**Comment by decembrya** [comment]
I will work on this

**Comment by RaduCStefanescu** [comment]
In progress @decembrya
