### ISSUE TITLE
[Notifications] Add new endpoint to get all sent notifications

### ISSUE THREAD

**Issue by aniri** [code4romania/monitorizare-vot#264]
Add new endpoint `GET /api/v1/notification/`. It should return all notifications from db. 

Fields to be returned for each notification:
- id
- title
- body
- channel
- sent by - depends on https://github.com/code4romania/monitorizare-vot/issues/265
- date
- list of observer ids the notification was sent to

The list should be paginated and sorted by date descending.

Permissions: 
- master admin (organizer) - should be able to view all sent notifications
- ngo admins (ngoadmin) should only view notifications that were sent by an admin from the same ngo

**Comment by LennartKleymann** [comment]
Hey I'd love to do that. 
Can you assign me @aniri?

**Comment by aniri** [comment]
hey @LennartKleymann any updates on this issue? thanks! :D

**Comment by dzoccarato** [comment]
Hi @aniri! I did something for this: https://github.com/code4romania/monitorizare-vot/pull/330, would you like to take a look? thanks!
