### ISSUE TITLE
[Polling stations] Add endpoint to get polling station info by id

### ISSUE THREAD

**Issue by aniri** [code4romania/monitorizare-vot#266]
New endpoint to be added:

- [ ] Add endpoint to view details about one polling station `GET api/v2/polling-station/{id}`

Permissions:
- only admins should have access to this endpoint.

**Comment by GabrielMajeri** [comment]
I want to work on this task. Is it still available?

**Comment by VladCuciureanu** [comment]
@aniri Is this task free for the taking? If so, I'd like to work on it.

**Comment by GabrielMajeri** [comment]
Hi @VladCuciureanu, since I didn't get an answer on this issue, I did make the changes but did not open a PR.

I've created one now, hopefully it can be reviewed.

**Comment by aniri** [comment]
@GabrielMajeri sorry, I somehow missed your first comment :( But thanks a lot for the PR, we'll review it soon!

@VladCuciureanu we have a lot of other open issues :D
