### ISSUE TITLE
[Notifications] Improve observers filtering 

### ISSUE THREAD

**Issue by aniri** [code4romania/monitorizare-vot#268]
When filtering observers from the notification screen, the `GET
/api/v1/observer/active` endpoint is used.

This endpoint is available for all admins (organizer & ngoadmin).

Please adjust the filtering of observers:
- organizer admin should receive all observers that meet the filtering criteria sent to `GET
/api/v1/observer/active`
- ngoadmins should only receive the observers that meet the filtering criteria **and are linked to the same ngo as the admin**

**Comment by ardelandrei** [comment]
I would like to try and solve this issue.

I want to make sure I understand this issue:

- one or more filtering criteria are not used? As far I can see, **CurrentlyCheckedIn** criteria is not applied. (How could it be applied?)

- if the **current user is an NGO admin**, the result must include only active observers who are part of the same NGO as the admin, and meet the filtering criteria?

Please have a little more patience, as it is the first issue I try to solve.

**Comment by aniri** [comment]
@ardelandrei  the `CurrentlyCheckedIn` is not currently used, it can be ignored for now :)
And yes, this is correct:
> if the current user is an NGO admin, the result must include only active observers who are part of the same NGO as the admin, and meet the filtering criteria?
There is a flag in the db that marks if an ngo is of type organizer or not.

This might have been implemented since posting this issue :thinking:

**Comment by ardelandrei** [comment]
Each observer's NGO identifier is checked against the request's NGO identifier. Not sure if an additional check is required on current user type and NGO admin type.

Is there a dev/staging environment where I can test this? Or to seed the local database with data?

**Comment by aniri** [comment]
@ardelandrei yes, the NGO type should be check also. you could add some test ngo/ngo admin in your local db and test this :)

**Comment by aniri** [comment]
hi @ardelandrei , did you get the change to check the current implementation and see if updates are needed on this issue? thanks!

**Comment by ardelandrei** [comment]
Hi @aniri , yes, I checked the current implementation. 

Unfortunately, I didn't had the time to test it on my local db.

I think there is a need for one update.
Just to clarify it:
From my understand, any type of user can access this endpoint. 
However, if the user is a **Ngo Admin**, he/she should receive only the active observers that are apart of the same Ngo as the Ngo Admin, right?

If this is the correct approach, there is a need for an additional check, as expressed above.

Please, confirm if this check is required from requirements perspective.

Thank you!

**Comment by aniri** [comment]
> Hi @aniri , yes, I checked the current implementation.
> 
> Unfortunately, I didn't had the time to test it on my local db.
> 
> I think there is a need for one update.
> Just to clarify it:
> From my understand, any type of user can access this endpoint.
> However, if the user is a **Ngo Admin**, he/she should receive only the active observers that are apart of the same Ngo as the Ngo Admin, right?
> 
> If this is the correct approach, there is a need for an additional check, as expressed above.
> 
> Please, confirm if this check is required from requirements perspective.
> 
> Thank you!

@ardelandrei there are two types on ngoadmins: regular and organizers (there is an organizer column in the ngoadmin db table).
Yes, any type of ngo admin users can access this endpoint.
If they are organizers they should receive all active observers, if they are regular ngo admins they should receive only the active observers that are part of the same Ngo.

Thanks!

**Comment by ardelandrei** [comment]
> Yes, any type of ngo admin users can access this endpoint.

Currently, there is no authentication or authorization policy applied to this endpoint, so any type of users, including anonymous users, can access this endpoint.
Should we enforce a policy to allow only 'NgoAdmin' type of users?

Then apply the filtering..
> If they are organizers they should receive all active observers, if they are regular ngo admins they should receive only the active observers that are part of the same Ngo.

Thank you!

**Comment by aniri** [comment]
@ardelandrei yep, exactly!

**Comment by aniri** [comment]
closing this as it was fixed :D
