### ISSUE TITLE
Get form endpoint should return also draft forms for admin accounts

### ISSUE THREAD

**Issue by aniri** [code4romania/monitorizare-vot#298]
Adjust the `GET ​/api​/v1​/form` to return different results:
- add a new query param of type bool `draft` & return forms filtered by it
- the query param is optional; if it is not set, please keep the current behavior (return only non draft forms)

**Comment by EmaSujova** [comment]
Hi, I am interested in working on this issue. Is it possible to assign it to me?

**Comment by aniri** [comment]
> Hi, I am interested in working on this issue. Is it possible to assign it to me?

@EmaSujova sure, thanks!

**Comment by aniri** [comment]
Hey @EmaSujova any updates on this? I was thinking of adjusting the requirements a bit to add a new query param `draft` and return the forms filtered like this. Instead of returning certain forms based on user type. Could you implement it like this? :D

**Comment by EmaSujova** [comment]
@aniri I will start work on that issue tomorrow.. yeah sure I can implement it like this :)

**Comment by aniri** [comment]
> @aniri I will start work on that issue tomorrow.. yeah sure I can implement it like this :)

@EmaSujova awesome! I will update the issues details then. Thanks!

**Comment by EmaSujova** [comment]
Hi @aniri, should I create a fork of these repository?

**Comment by aniri** [comment]
@EmaSujova yes, you have to make a fork, make the changes in your fork and then open a pull request :)
