### ISSUE TITLE
Add one more filter on GET ​/api​/v1​/answers

### ISSUE THREAD

**Issue by aniri** [code4romania/monitorizare-vot#299]
It should be able to view the answers by observer phone number.

**Comment by bjm-csse** [comment]
Hi, I am interested in working on this, thanks!

**Comment by aniri** [comment]
> Hi, I am interested in working on this, thanks! Would you be interested in assigning this to me?

@bjm-csse sure, thanks!

**Comment by aniri** [comment]
hey @bjm-csse any update on this issue? :smile:

**Comment by bjm-csse** [comment]
@aniri Sorry I was out of town this last week/weekend. I plan to tackle it this week!

**Comment by bjm-csse** [comment]
@aniri I think I have the changes needed to close this issue but I have been unable to test it. The first barrier being authorizing with the API. The endpoint requires a user, password, and unique id. How do I go about getting these so I can authorize? Also to make sure I'm on the correct path I haven't used Mediatr with the CQRS pattern yet but I'm trying my hardest to understand it, can you check out my changes? Thanks! https://github.com/bjm-csse/monitorizare-vot/tree/feature/filter-phonenum

**Comment by aniri** [comment]
hey @bjm-csse ! to be able to login you need to add to your local db an ngo and an ngo admin account connected to that ngo. and then only send the user and password set for it from swagger using the access/authorize method to get an auth token to use on the other requests. it is difficult for me to see the code changes like that. could you open a pull request so it would be easier to see the newly added code? thanks!!
