### ISSUE TITLE
Finalize PUT for forms endpoint implementation

### ISSUE THREAD

**Issue by aniri** [code4romania/monitorizare-vot#310]
The implementation for the PUT endpoint was started in this branch https://github.com/code4romania/monitorizare-vot/tree/feature/put_for_forms , in PR https://github.com/code4romania/monitorizare-vot/pull/165 .

It needs some updates before being merged into develop:
- If the form already has sections, questions and options they should be updated. Currently new sections, questions and options are added for it. Only newly added sections, questions and options should be added, old ones should be updated.

_Deleting sections, questions and options will be handled in a different issue. The update command should only update/add new info to forms._

**Comment by sandrohanea** [comment]
Hi @aniri!
If that's ok, I can take this one(you can assign it to me). I see that PR #165 was already merged so I'll create another one for this.

**Comment by aniri** [comment]
Hey @sandrohanea ! And thanks! Yes, the old PR was merged in a new branch https://github.com/code4romania/monitorizare-vot/tree/feature/put_for_forms , please make a PR to that branch and we'll merge all the changes into develop after testing on that branch.

**Comment by sandrohanea** [comment]
I'll take my time to also refactor a bit the _Form_ service.
I see that commands and command handlers are in the Queries namespace/folder and sometimes commands are named queries.

**Comment by aniri** [comment]
@sandrohanea sounds like a good plan :pray: thanks! Yes, I also noticed there's a bit of chaos there :smile:
