### ISSUE TITLE
Investigate if data export speed could be improved

### ISSUE THREAD

**Issue by aniri** [code4romania/monitorizare-vot#317]
If there are many answers in the db, the data export `GET ​/api​/v1​/export​/all`, is very slow and sometimes timeouts/crashes.

Please check if it could be improved. Maybe consider exporting as csv instead of xlsx?

**Comment by dzoccarato** [comment]
Hi, I am interested in working on this, thanks! Would you be interested in assigning this to me?
Just to make me an idea, when you talk about "many answers", what are you thinking about? 10K, 100K,1000K, ... ? On your tests what is the timing you got from this api ? (to understand if my changes can help you or not)

**Comment by aniri** [comment]
@dzoccarato hey :) it takes a few seconds to generate xls files over 1m. I'll have to get back to you with an extimated number of results for that. and sometimes it just gives an error an no xls file is generated.

**Comment by aniri** [comment]
50k lines in an xls of 2M was very slow and often crashed for example.

**Comment by dzoccarato** [comment]
@aniri thanks! I'll cames back to you asap!

**Comment by dzoccarato** [comment]
Hi @aniri , I did something for this, please check the PR #319 

just a little note:
"_it works on my machine_" ;), because I've used local environment, please let me know if this solution is appreciable from your point of view or if I misunderstand the values of your test cases you provide me on your previous comment

**Comment by aniri** [comment]
awesome news @dzoccarato . I'll test it and get back to you! Thanks for your help!!
