### ISSUE TITLE
[BUG] The import polling stations feature fails to import the last polling station from the xlsx file

### ISSUE THREAD

**Issue by aniri** [code4romania/monitorizare-vot#359]
All the rows are imported correctly, but not the last one :/

**Comment by idormenco** [comment]
@aniri please provide uploaded file

**Comment by aniri** [comment]
@idormenco you can test with the `RSV – TOTAL ALEGERI PARLAMENTARE – 06.11.2020` file from here https://www.roaep.ro/management-electoral/geografie-electorala/registrul-sectiilor-de-votare/
