### ISSUE TITLE
Dynamic hotline number

### ISSUE THREAD

**Issue by KrzysztofMadejski** [code4romania/monitorizare-vot#48]
So each volunteer will reach out his/her coordinator. It would require a list of coordinators + phone numbers and assigning those to volunteers.

We might also do a dynamic call center with forwarded calls from one general number. I wonder if you have an experience with that?

**Comment by KrzysztofMadejski** [comment]
What we did in the end is to have a html screen listing telephone number for various cases:
- if your in district A then call person 1
- if this relates to media coverage call person 2
- if this is a technical issue call other

It turned out that observation center ppl changed in the meantime so it would be cool to be able to update it online via the DB, but it's definietely low priority.

**Comment by aniri** [comment]
Issue added in features of new version of the app.
