### ISSUE TITLE
Update API to 2.0

### ISSUE THREAD

**Issue by KrzysztofMadejski** [code4romania/monitorizare-vot#50]
- [ ] translate fields to English
- [ ] more meaningful Version: Major, minor, patch: [code](https://github.com/epforgpl/monitorizare-vot-android/blob/be378fc1ac1b1d55fe9cf7d0b75f79bcba8ff819/app/src/main/java/ro/code4/monitorizarevot/net/model/Version.java#L17)
- [ ] Question type as enum/string [code](https://github.com/epforgpl/monitorizare-vot-android/blob/be378fc1ac1b1d55fe9cf7d0b75f79bcba8ff819/app/src/main/java/ro/code4/monitorizarevot/net/model/Question.java#L33)
- [ ] Functions returning empty response should be void/null instead of empty custom class [see NetworkService](https://github.com/epforgpl/monitorizare-vot-android/blob/be378fc1ac1b1d55fe9cf7d0b75f79bcba8ff819/app/src/main/java/ro/code4/monitorizarevot/net/NetworkService.java#L144)
- [Support different languages and cultures](https://github.com/code4romania/monitorizare-vot-android/issues/26)
  - [ ] Dynamic forms served by API
  - [ ] Rural/urban, male/female should be a dynamic form, not hardcoded
  - [ ] Administrative boundaries served dynamically through API

**Comment by RaduCStefanescu** [comment]
Issue added in features of new version of the app.
