### ISSUE TITLE
BlobStorage portability

### ISSUE THREAD

**Issue by KrzysztofMadejski** [code4romania/monitorizare-vot#53]
Is BlobStorage an Azure only thing? S3 would be a more portable choice.

**Comment by KrzysztofMadejski** [comment]
Also: How Container should be set up? Should it be private without anonymous access or is image/video shared somewhere publicly?

**Comment by bvizureanu** [comment]
Related to #98

**Comment by RaduCStefanescu** [comment]
Fixed by Bogdan's PR: 
https://github.com/code4romania/monitorizare-vot/commit/5120120a21d1dfe5a23a78460f8b26d79d5d2e1e
