### ISSUE TITLE
Creating database tables and seeding them with data should be 2 different commands

### ISSUE THREAD

**Issue by KrzysztofMadejski** [code4romania/monitorizare-vot#58]
Ideally they could be run from the command line, sth like `dotnet run db-create` `dotnet run db-seed`

**Comment by RaduCStefanescu** [comment]
This one is fixed already, please have a look at Bogdan's PR:
https://github.com/code4romania/monitorizare-vot/commit/903094152373fe41063d22207a47a0ef4f70caf6
