### ISSUE TITLE
Allow to login, but not fill in the forms

### ISSUE THREAD

**Issue by KrzysztofMadejski** [code4romania/monitorizare-vot#59]
I see there is "La ora asta observatorii ar trebui sa doarma! :) Aplicatia va fi functionala la ora 6. Asigura-te ca ai cea mai recenta versiune. Fa un update!" error when user can't be logged in, but logging in and starting observation should be two different actions, see https://github.com/code4romania/monitorizare-vot-android/issues/52

**Comment by KrzysztofMadejski** [comment]
Hack: use application settings to change the Salt temporarily.

**Comment by KrzysztofMadejski** [comment]
But it's just a hack. It would be great if logging in would be working, but observers would get a screen saying "observation starts at.. ".

**Comment by RaduCStefanescu** [comment]
Issue added in features of new version of the app.
