### ISSUE TITLE
API errors & i18n

### ISSUE THREAD

**Issue by KrzysztofMadejski** [code4romania/monitorizare-vot#60]
API should be sending unique error codes, best if string-typed. If numerical then optionally with some message, but the clients (Android, iOS, dashboard) should be responsible for displaying a message in language that is chosen by user.

Case of untranslated error: `La ora asta observatorii ar trebui sa doarma! :) Aplicatia va fi functionala la ora 6. Asigura-te ca ai cea mai recenta versiune. Fa un update!`

Proposition of standard error format:
```json
{
"code": "OBSERVATION_NOT_OPEN",
"message": "Observation is not happening. Come back during the election day on %{election_day}." // optional, might be helpful for standardizing it among many clients
"params": { // any params needed to format message
  "election_day": "21st October"
  }
}
```

**Comment by RaduCStefanescu** [comment]
Issue added in features of new version of the app.
