### ISSUE TITLE
Dynamic forms

### ISSUE THREAD

**Issue by KrzysztofMadejski** [code4romania/monitorizare-vot#67]
So one can define more than three forms

**Comment by bvizureanu** [comment]
we just had a debate around this feature and the mobile apps should be enhanced with this.
I would move this in their respective repo or as a project level feature
The backend should now support any number of forms; You just need to add the values to the questions table

**Comment by KrzysztofMadejski** [comment]
True that `/api/v1/formular/versiune` returns all defined versions.

Nevertheless I'm missing two things in the API:
- [ ] Longer `Code`. Now it's only two chars and we wanted to be able to put for example `C3a`
- [ ] Descriptions - More forms means we need to store descriptions somewhere. They should be added to `FormVersions` table. 

Again, I'm able to hack it / hard-code it in the apps, but that's not a long-term solution.

**Comment by aniri** [comment]
solved in latest deployment of app.
