### ISSUE TITLE
Dynamic administrative boundaries

### ISSUE THREAD

**Issue by KrzysztofMadejski** [code4romania/monitorizare-vot#68]
Now Counties are hard-coded both in the android app and in the API. They should be defined dynamically and allow for multiple levels. In Poland one should choose first `voidevoiship`, then `powiat`, then `gmina` and only in the end the polling station.

**Comment by KrzysztofMadejski** [comment]
I just thought that in the meantime I can hack it/fool it by defining multiple layers in the android app, but sending a complex code to the API, such as "PL-Mazowsze-Warszawa". Does codes in the API and the app (hardcoded) have to match?

**Comment by KrzysztofMadejski** [comment]
I propose to extend `County` with two attributes `int level` and `int parent_id` so it would allow for any number of levels of administrative boundaries.

**Comment by bvizureanu** [comment]
I will have to remove the enum check from the code for this (this was a tiny mechanism to check the validity of the model received)

**Comment by KrzysztofMadejski** [comment]
There is no option to flatten the list. We have unique numbering 1-... for each lowest level administrative boundary, meaning we have 2478 polling stations with number 1. I don't foresee creating a select box with 2478 options.. 

As I've mentioned before I could hack it for now with a hierarchy coded in Android, but that's not a long-term solution.

**Comment by RaduCStefanescu** [comment]
Issue added in features of new version of the app.
