### ISSUE TITLE
Free text (explaining a situation)

### ISSUE THREAD

**Issue by KrzysztofMadejski** [code4romania/monitorizare-vot#69]
Use case: if observer choose options A we want to inquire what happened exactly?

Now it is coded as a `IsFreeText` attribute of the `Option`, which makes little sense, because we might want to inquire on different options depending on the question. Sometimes on `Yes`, sometimes on `No`, sometimes on sth different.

IMHO the `OptionsToQuestions` class should be enhanced with:
- `ask_more bit default 0 not null`
- `ask_more_hint nvarchar(max)`

**Comment by KrzysztofMadejski** [comment]
I've hacked that by creating two options in such cases, such as "Yes" and "Yes, say more". But the results might be harder to analyze because of that (depending on the export)

**Comment by KrzysztofMadejski** [comment]
In the real deployment we resolved it by making multiple questions, such as:
1. Was the situation happening? yes / no
2. If yes then please describe who was doing that.

Which has its upsides (clear coding for extra questions, ability to make more detailed questions) and downsides (observers see that even if they clicked other option - "no" in above case).

I believe the two existing ways (different option naming + extra questions) should land in the documentation concerning form creation #40

**Comment by RaduCStefanescu** [comment]
Issue added in features of new version of the app.
