### ISSUE TITLE
/formular doesn't serve Section.id - a primary key

### ISSUE THREAD

**Issue by KrzysztofMadejski** [code4romania/monitorizare-vot#72]
Try: localhost:8080/api/v1/formular?idformular=A
There is section.code returned, but not the section.id which is unique in the database. 
If section code should be unique then the database definitions should be corrected. If it shouldn't be unique then API needs extending and at least Android app needs to use it.

**Comment by aniri** [comment]
fixed in commit https://github.com/code4romania/monitorizare-vot/commit/7fe6996b671d1150726395969e5c0e77086fe556
