### ISSUE TITLE
Make migrations easy to call from Docker

### ISSUE THREAD

**Issue by KrzysztofMadejski** [code4romania/monitorizare-vot#73]
- If that's not a problem they should be available from the final Docker image
- Document how to run it
- Should they run automatically on running image? or should it be a separate command?

My gut would say to make a dedicated `migrations.sh` script:
```sh
#!/bin/bash
set -e

envsubst "`printf '${%s} ' $(bash -c "compgen -A variable")`" < appsettings.json.template > appsettings.json

dotnet VotingIrregularities.Api.dll
```
It ciukd be called from outside just by providing this script name to `docker run --it mv-api --env .env.docker`. One should check if this won't override original appsettings.json in case fewer env settings are provided. Maybe new container should be created for that..

**Comment by RaduCStefanescu** [comment]
Issue added in features of new version of the app.
