### ISSUE TITLE
Warning: Missing XML comment for publicly visible type

### ISSUE THREAD

**Issue by KrzysztofMadejski** [code4romania/monitorizare-vot#75]
I'm getting shitload of such warnings on `restore`

One example:
`Controllers/Formular.cs(20,16): warning CS1591: Missing XML comment for publicly visible type or member 'Formular.Formular(IMediator, IConfigurationRoot)' [/app/src/VotingIrregularities.Api/VotingIrregularities.Api.csproj]`

**Comment by KrzysztofMadejski** [comment]
Are the Swagger docs finished? I remember checking it once and they were not fully corresponding to the API.

**Comment by aniri** [comment]
closing as it refers to old version of the code.
