### ISSUE TITLE
Add option to disable mobileDeviceId checking

### ISSUE THREAD

**Issue by KrzysztofMadejski** [code4romania/monitorizare-vot#90]

**Comment by KrzysztofMadejski** [comment]
Done, now only documentation is needed.

**Comment by KrzysztofMadejski** [comment]
I've added that, but then right before deploy argued against it on the Slack. I believe we need to clarify one thing. 

During observation we had a following scenario:
- an observer uses an app to fill in forms
- at one point the device crashes and each attempt to open it again result in an crash upfront - the app is unusable
- we ask observer to delete app data / uninstall the app and login again

Question: What happens when an observer logs in on the same (or another device) onto the same account, but with a fresh app with no data locally?
1) The data already being present on the server is synced in onto the device. The observer can continue to fill in the form. Then everything is ok.
2) The data is not synced in onto the device. Observer fills in a new answer and the current device's data (with one answer) is being sent to the server effectively wiping out all of the data already entered. This is very bad!

Being afraid of very harmful consequences of the option 2 in the end I've kept device lock in and created new accounts for observers that had crashed apps. If the ecosystem now behaves in a way 2 then we should develop syncing-in feature and put some NOTICE info next to this option in the documentation.


BTW: This issue shouldn't be closed unless the setting is documented here: https://github.com/code4romania/monitorizare-vot/wiki/Application-Settings

**Comment by aniri** [comment]
closing this one as will be documented in https://github.com/code4romania/monitorizare-vot/issues/100

**Comment by KrzysztofMadejski** [comment]
Hi Irina,

I really appreciate you're cleaning backlog and providing feedback. Thanks!

And all the best!

wt., 6 paź 2020, 08:43 użytkownik Irina Borozan <notifications@github.com>
napisał:

**Comment by aniri** [comment]
@KrzysztofMadejski hey!! I've finally found some time for working on the docs and setup info :smiley: So I'll soon add a lot of new stuffs to the wiki :D
