### ISSUE TITLE
Notes sent from questions in Android are not linked to questions in DB

### ISSUE THREAD

**Issue by KrzysztofMadejski** [code4romania/monitorizare-vot#91]
Not sure yet if it's Android or API issue.

**Comment by KrzysztofMadejski** [comment]
API issue. `Question.Id = 0` is [treated as note not linked with question](https://github.com/code4romania/monitorizare-vot/blob/master/private-api/app/src/VotingIrregularities.Domain/NotaAggregate/AdaugaNotaHandler.cs#L28), so children remember, count your questions from 1!

**Comment by KrzysztofMadejski** [comment]
Add a DB `CHECK` to make sure other values are not inserted in the DB.

**Comment by bvizureanu** [comment]
Can we close this?

We'll add a UI/api for altering the form structure in the Admin/NGO app, That should take care of conventions like these.

**Comment by KrzysztofMadejski** [comment]
Would be safer to write down the rule explicitly in the DB as well.

**Comment by aniri** [comment]
closing this as it was fixed on android
